export {default as Header} from './Header/Header'
export {default as Hero} from './Hero/Hero'
export {default as MostPopular} from './MostPopular/MostPopular'
export {default as Products} from './Products/Products'
export {default as Services} from './Services/Services'
export {default as Footer} from './Footer/Footer'